# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 462)
        Dialog.setAutoFillBackground(False)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 531, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_getdata = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_getdata.setGeometry(QtCore.QRect(10, 20, 211, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_getdata.setFont(font)
        self.pushButton_getdata.setObjectName("pushButton_getdata")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(30, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.textEdit_filepath = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_filepath.setEnabled(False)
        self.textEdit_filepath.setGeometry(QtCore.QRect(230, 40, 291, 41))
        self.textEdit_filepath.setObjectName("textEdit_filepath")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(230, 20, 101, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.doubleSpinBox_tracklength = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_tracklength.setEnabled(False)
        self.doubleSpinBox_tracklength.setGeometry(QtCore.QRect(120, 60, 101, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_tracklength.setFont(font)
        self.doubleSpinBox_tracklength.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_tracklength.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tracklength.setSpecialValueText("")
        self.doubleSpinBox_tracklength.setDecimals(4)
        self.doubleSpinBox_tracklength.setMaximum(1000.0)
        self.doubleSpinBox_tracklength.setSingleStep(0.0)
        self.doubleSpinBox_tracklength.setObjectName("doubleSpinBox_tracklength")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 110, 271, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(-10, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(60, 110, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.spinBox_dampingfac = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_dampingfac.setGeometry(QtCore.QRect(160, 110, 101, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_dampingfac.setFont(font)
        self.spinBox_dampingfac.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_dampingfac.setObjectName("spinBox_dampingfac")
        self.doubleSpinBox_shockdisp = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_shockdisp.setGeometry(QtCore.QRect(160, 20, 101, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_shockdisp.setFont(font)
        self.doubleSpinBox_shockdisp.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_shockdisp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_shockdisp.setSpecialValueText("")
        self.doubleSpinBox_shockdisp.setDecimals(4)
        self.doubleSpinBox_shockdisp.setMaximum(1.0)
        self.doubleSpinBox_shockdisp.setSingleStep(0.0)
        self.doubleSpinBox_shockdisp.setObjectName("doubleSpinBox_shockdisp")
        self.doubleSpinBox_shockspring = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_shockspring.setGeometry(QtCore.QRect(160, 50, 101, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_shockspring.setFont(font)
        self.doubleSpinBox_shockspring.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_shockspring.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_shockspring.setSpecialValueText("")
        self.doubleSpinBox_shockspring.setDecimals(4)
        self.doubleSpinBox_shockspring.setMaximum(1000.0)
        self.doubleSpinBox_shockspring.setSingleStep(0.0)
        self.doubleSpinBox_shockspring.setObjectName("doubleSpinBox_shockspring")
        self.doubleSpinBox_tirespring = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_tirespring.setGeometry(QtCore.QRect(160, 80, 101, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_tirespring.setFont(font)
        self.doubleSpinBox_tirespring.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_tirespring.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tirespring.setSpecialValueText("")
        self.doubleSpinBox_tirespring.setDecimals(4)
        self.doubleSpinBox_tirespring.setMaximum(1000.0)
        self.doubleSpinBox_tirespring.setSingleStep(0.0)
        self.doubleSpinBox_tirespring.setObjectName("doubleSpinBox_tirespring")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 110, 251, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(50, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(40, 110, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.doubleSpinBox_bodyweight = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_bodyweight.setGeometry(QtCore.QRect(140, 20, 101, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_bodyweight.setFont(font)
        self.doubleSpinBox_bodyweight.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_bodyweight.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_bodyweight.setSpecialValueText("")
        self.doubleSpinBox_bodyweight.setDecimals(4)
        self.doubleSpinBox_bodyweight.setMaximum(1000.0)
        self.doubleSpinBox_bodyweight.setSingleStep(0.0)
        self.doubleSpinBox_bodyweight.setObjectName("doubleSpinBox_bodyweight")
        self.doubleSpinBox_CG = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_CG.setGeometry(QtCore.QRect(140, 50, 101, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_CG.setFont(font)
        self.doubleSpinBox_CG.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_CG.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_CG.setSpecialValueText("")
        self.doubleSpinBox_CG.setDecimals(4)
        self.doubleSpinBox_CG.setMaximum(1.0)
        self.doubleSpinBox_CG.setSingleStep(0.0)
        self.doubleSpinBox_CG.setObjectName("doubleSpinBox_CG")
        self.doubleSpinBox_wheelweight = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_wheelweight.setGeometry(QtCore.QRect(140, 80, 101, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_wheelweight.setFont(font)
        self.doubleSpinBox_wheelweight.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_wheelweight.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_wheelweight.setSpecialValueText("")
        self.doubleSpinBox_wheelweight.setDecimals(4)
        self.doubleSpinBox_wheelweight.setMaximum(1000.0)
        self.doubleSpinBox_wheelweight.setSingleStep(0.0)
        self.doubleSpinBox_wheelweight.setObjectName("doubleSpinBox_wheelweight")
        self.doubleSpinBox_tireradius = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_tireradius.setGeometry(QtCore.QRect(140, 110, 101, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_tireradius.setFont(font)
        self.doubleSpinBox_tireradius.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_tireradius.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tireradius.setSpecialValueText("")
        self.doubleSpinBox_tireradius.setDecimals(4)
        self.doubleSpinBox_tireradius.setMaximum(10.0)
        self.doubleSpinBox_tireradius.setSingleStep(0.0)
        self.doubleSpinBox_tireradius.setObjectName("doubleSpinBox_tireradius")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 260, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(0, 50, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.spinBox_wishboneN = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_wishboneN.setGeometry(QtCore.QRect(140, 50, 101, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_wishboneN.setFont(font)
        self.spinBox_wishboneN.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_wishboneN.setMinimum(1)
        self.spinBox_wishboneN.setMaximum(10)
        self.spinBox_wishboneN.setObjectName("spinBox_wishboneN")
        self.doubleSpinBox_wblength = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_wblength.setGeometry(QtCore.QRect(140, 20, 101, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_wblength.setFont(font)
        self.doubleSpinBox_wblength.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_wblength.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_wblength.setSpecialValueText("")
        self.doubleSpinBox_wblength.setDecimals(4)
        self.doubleSpinBox_wblength.setMaximum(10.0)
        self.doubleSpinBox_wblength.setSingleStep(0.0)
        self.doubleSpinBox_wblength.setObjectName("doubleSpinBox_wblength")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(270, 260, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(40, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(50, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.doubleSpinBox_initXvel = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox_initXvel.setGeometry(QtCore.QRect(150, 20, 111, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_initXvel.setFont(font)
        self.doubleSpinBox_initXvel.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_initXvel.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_initXvel.setSpecialValueText("")
        self.doubleSpinBox_initXvel.setDecimals(4)
        self.doubleSpinBox_initXvel.setMaximum(1000.0)
        self.doubleSpinBox_initXvel.setSingleStep(0.0)
        self.doubleSpinBox_initXvel.setObjectName("doubleSpinBox_initXvel")
        self.doubleSpinBox_initYvel = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox_initYvel.setGeometry(QtCore.QRect(150, 50, 111, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_initYvel.setFont(font)
        self.doubleSpinBox_initYvel.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_initYvel.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_initYvel.setSpecialValueText("")
        self.doubleSpinBox_initYvel.setDecimals(4)
        self.doubleSpinBox_initYvel.setMaximum(1000.0)
        self.doubleSpinBox_initYvel.setSingleStep(0.0)
        self.doubleSpinBox_initYvel.setObjectName("doubleSpinBox_initYvel")
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 350, 531, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_solve = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_solve.setGeometry(QtCore.QRect(10, 20, 211, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_solve.setFont(font)
        self.pushButton_solve.setObjectName("pushButton_solve")
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setGeometry(QtCore.QRect(220, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.doubleSpinBox_sag = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_sag.setEnabled(False)
        self.doubleSpinBox_sag.setGeometry(QtCore.QRect(410, 20, 111, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_sag.setFont(font)
        self.doubleSpinBox_sag.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_sag.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sag.setSpecialValueText("")
        self.doubleSpinBox_sag.setDecimals(4)
        self.doubleSpinBox_sag.setMaximum(1000.0)
        self.doubleSpinBox_sag.setSingleStep(0.0)
        self.doubleSpinBox_sag.setObjectName("doubleSpinBox_sag")
        self.pushButton_exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_exit.setGeometry(QtCore.QRect(420, 420, 111, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_clear = QtWidgets.QPushButton(Dialog)
        self.pushButton_clear.setGeometry(QtCore.QRect(300, 420, 111, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Ground Data"))
        self.pushButton_getdata.setText(_translate("Dialog", "Load Ground Coords"))
        self.label_9.setText(_translate("Dialog", "Track Length"))
        self.label_11.setText(_translate("Dialog", "Filepath Chosen"))
        self.doubleSpinBox_tracklength.setSuffix(_translate("Dialog", " m"))
        self.groupBox_2.setTitle(_translate("Dialog", "Suspension Data"))
        self.label_8.setText(_translate("Dialog", "Max Shock Displacement"))
        self.label_6.setText(_translate("Dialog", "Tire Stiffness"))
        self.label_5.setText(_translate("Dialog", "Shock Springrate"))
        self.label_7.setText(_translate("Dialog", "Shock Damping Factor"))
        self.doubleSpinBox_shockdisp.setSuffix(_translate("Dialog", " m"))
        self.doubleSpinBox_shockspring.setSuffix(_translate("Dialog", " N m"))
        self.doubleSpinBox_tirespring.setSuffix(_translate("Dialog", " N m"))
        self.groupBox_3.setTitle(_translate("Dialog", "Vehicle Data"))
        self.label.setText(_translate("Dialog", "Body Weight"))
        self.label_2.setText(_translate("Dialog", "CG Location"))
        self.label_3.setText(_translate("Dialog", "Wheel & Tire Weight"))
        self.label_4.setText(_translate("Dialog", "Tire Radius"))
        self.doubleSpinBox_bodyweight.setSuffix(_translate("Dialog", " kg"))
        self.doubleSpinBox_CG.setSuffix(_translate("Dialog", " m"))
        self.doubleSpinBox_wheelweight.setSuffix(_translate("Dialog", " kg"))
        self.doubleSpinBox_tireradius.setSuffix(_translate("Dialog", " m"))
        self.groupBox_4.setTitle(_translate("Dialog", "Wishbone Data"))
        self.label_10.setText(_translate("Dialog", "Wishbone Length"))
        self.label_12.setText(_translate("Dialog", "Number of Wishbones"))
        self.doubleSpinBox_wblength.setSuffix(_translate("Dialog", " m"))
        self.groupBox_5.setTitle(_translate("Dialog", "Initial Conditions"))
        self.label_13.setText(_translate("Dialog", "Velocity in the X"))
        self.label_14.setText(_translate("Dialog", "Velocity in the Y"))
        self.doubleSpinBox_initXvel.setSuffix(_translate("Dialog", " m/s"))
        self.doubleSpinBox_initYvel.setSuffix(_translate("Dialog", " m/s"))
        self.groupBox_6.setTitle(_translate("Dialog", "Calculated Data"))
        self.pushButton_solve.setText(_translate("Dialog", "Solve"))
        self.label_15.setText(_translate("Dialog", "Calculated Suspension Sag"))
        self.doubleSpinBox_sag.setSuffix(_translate("Dialog", " m"))
        self.pushButton_exit.setText(_translate("Dialog", "Exit"))
        self.pushButton_clear.setText(_translate("Dialog", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

